# -*- coding: utf-8 -*-
"""app.py.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10YqfYF9T41z0ITUArJn1ylwPKjrNJgaD
"""

uploaded = files.upload()

import pandas as pd
import streamlit as st

st.title("Heart Disease Analytics Dashboard")

# Make sure you uploaded the CSV before running this
df = pd.read_csv("CVD_cleaned_small.csv")

st.subheader("Preview of Dataset")
st.dataframe(df.head())

st.subheader("Heart Disease Cases by Age Category")
age_counts = df[df["Heart_Disease"] == "Yes"]["Age_Category"].value_counts()
st.bar_chart(age_counts)

st.subheader("Heart Disease by Gender")
gender_counts = df[df["Heart_Disease"] == "Yes"]["Sex"].value_counts()
st.bar_chart(gender_counts)

